seed: 42
model:
  name: 'ResUNetWithTabular'
  cont_features: 32
  bin_features: 6

training:
  lr: 0.005
  batch_size: 32
  epochs: 50
  train_steps: 500
  valid_steps: 250
  patience: 10
  max_norm: 1

data:
  image_dir: '../data/train-image/image'
  metadata_file: '../data/ppcMetadata.csv'

logging:
  log_dir: 'logs'