seed: 42

model:
  name: 'ResUNetWithTabular'
  cont_features: 31
  bin_features: 6

testing:
  test: True
  test_size: 1059
  batch_size: 10
  num_workers: 5
  ck: null
  run: null

training:
  lr: 0.005
  weight_decay: 0.01
  batch_size: 32
  num_workers: 20
  epochs: 50
  train_steps: 500
  valid_steps: 250
  patience: 5
  max_norm: 1
  norm_type: 1

data:
  image_dir: '../data/train-image/image'
  metadata_file: '../data/ppcMetadata.csv'

logging:
  log_dir: 'logs'